[Hexagon] Support both 1-d and 2-d VTCM allocations
apache/tvm pull request #10846
Opened 2022-03-31 17:04 UTC by Lunderberg

This change allows allocation of buffers with `"global.vtcm"` to be either 1-d (flat) or 2-d (non-flat) memory allocations.

2022-03-31 20:48 UTC, adstraw requested changes
LGTM; just need to clean up some unused code.

2022-03-31 20:48 UTC, adstraw commented on src/runtime/hexagon/hexagon/hexagon_buffer.h
> +  // size_t GetNumAllocs() { return nallocs_; }
remove

2022-03-31 20:48 UTC, adstraw commented on src/runtime/hexagon/hexagon/hexagon_buffer.h
> +  size_t GetBufferDimension() { return ndim_; }
remove, not called

2022-04-01 02:07 UTC, Lunderberg commented on src/runtime/hexagon/hexagon/hexagon_buffer.h
> +  size_t GetBufferDimension() { return ndim_; }
Thank you, and done.

2022-04-01 02:08 UTC, Lunderberg commented on src/runtime/hexagon/hexagon/hexagon_buffer.h
> +  // size_t GetNumAllocs() { return nallocs_; }
Thank you, and done.

2022-04-01 16:37 UTC, kparzysz-quic approved these changes

2022-04-01 16:37 UTC, kparzysz-quic commented on src/runtime/hexagon/hexagon/hexagon_buffer.h
> +   * The return type depends on the buffer being
This comment looks truncated.

2022-04-01 16:37 UTC, merged