[ci][docs] Seed autotvm tutorial
apache/tvm pull request #11147
Opened 2022-04-27 18:13 UTC by driazati

The runtime on this one varies a lot, so this tries adding a seed to get it consistent

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

2022-04-27 19:52 UTC, mbaret approved these changes
lgtm

2022-05-11 18:00 UTC, areusch requested changes

2022-05-11 18:00 UTC, areusch commented on gallery/tutorial/autotvm_relay_x86.py
> +np.random.seed(0)
can you comment why we are doing this in the file?

2022-05-12 20:58 UTC, areusch approved these changes

2022-05-12 20:58 UTC, merged