[Relay] Support i16, f16 scalars in Relay text
apache/tvm pull request #11224
Opened 2022-05-05 21:59 UTC by mbs-octoml

While testing fp16 models for Collage discovered the Relay text
format did not support f16. While adding that cleaned up scalar handling
in general. However I left two inlined tests for 'is simple const'
in place (fuse_ops.cc and memory_alloc.cc) since it's not clear whether
they should remain specific to just {i,f}{32,64} or whether they can
be replaced with the support::IsSimpleScalar central predicate.

2022-05-10 09:04 UTC, Mousius requested changes
I think this is generally an improvement, but I'm curious whether we could cover more of the error scenarios in test cases? There's three different diagnostic errors for both int and float plus the clipping errors - though I'm unsure how easy it is to trigger them with current testing infrastructure.

2022-05-18 22:45 UTC, mbs-octoml commented on tests/python/relay/test_ir_text_printer.py
> +def test_large_graph():
Yeah, turned it on expecting CI to fail but all was well. Job well done indeed.

2022-05-18 23:44 UTC, mbs-octoml commented
Thanks @Mousius (and sorry for the delay, been off an a separate adventure). I think the range checking testing is ok, and I added range checks for fp16 too. For the LOG(FATALS) I'll add cc tests since it's tricky to tickle the failures via python. stand by.

2022-05-19 11:36 UTC, Mousius approved these changes

2022-05-19 11:37 UTC, merged

2022-05-19 11:38 UTC, Mousius commented
Thanks @mbs-octoml 😸  nice clean up!