The change allows to increase performance in multi-thread environment.
apache/tvm pull request #12323
Opened 2022-08-05 16:19 UTC by shtinsa

In this case data locality is improved and it may have positive effect to final inference in case of MT execution.

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

2022-08-05 18:31 UTC, shtinsa commented
![res_dlrm-0805_three](https://user-images.githubusercontent.com/88086617/183139547-0f2bca2a-c535-4851-a9c5-230662ac591f.png)
The picture contains perf improvements in case of DLRM model

2022-08-05 18:49 UTC, shtinsa commented
@jwfromm @tkonolige could you please review? the changes may increase memory usage but the same time it decrease data crashing within the cpu caches.

2022-08-23 09:27 UTC, apeskov commented
The word "Global" means that it's a global singleton. Changing semantic to thread local will confuse developers. 

Moreover, this patch works only because you initialise VirtualMachine modules form separate threads. That is not mandatory behaviour. Customer may create a set of VirtualMachine in main thread and after that assign them to worker sub threads.

This change is good enough to demonstrate possibility of advance memory management in case of multi instance execution. But it cannot be merged as is.

2022-08-23 09:28 UTC, apeskov requested changes

2022-08-23 09:28 UTC, apeskov commented on src/runtime/vm/memory_manager.cc
> +std::shared_ptr<MemoryManager> MemoryManager::Global() {
"Global" means global. Thread local object is not obvious behaviour for this method.

2025-02-06 20:18 UTC, closed without merging