[Target] Add Target Parser for Arm(R) Cortex(R) A-Profile CPUs
apache/tvm pull request #12454
Opened 2022-08-16 09:35 UTC by Mousius

This implements an initial Target Parser which aims to consolidate architecture feature detection from a few different places:
* https://github.com/apache/tvm/blob/d2db9cb0d839e32778f461b77e59f6418282a511/python/tvm/topi/arm_cpu/arm_utils.py#L24-L70
* https://github.com/apache/tvm/blob/02fbaf0ed9120a8f95155e63de42459f230584aa/python/tvm/relay/qnn/op/legalizations.py#L350-L359
* https://github.com/apache/tvm/blob/b542724873140bb051492530d97a78b9b7b7983d/python/tvm/relay/op/strategy/arm_cpu.py#L232

A further patch will remove all of the above and replace usages with the `.features` map.

2022-08-16 09:35 UTC, Mousius commented
cc @u99127 for review 😸

2022-10-13 14:48 UTC, u99127 requested changes
Sorry about the time it has taken to get around to this :) 

If I could request a few changes , then I'm good .

2022-10-20 08:58 UTC, u99127 approved these changes
LGTM.

2022-10-20 09:17 UTC, lhutton1 approved these changes
LGTM!

2022-10-20 09:24 UTC, merged