[MicroTVM] fix compile error when the compiler implements char as unsigned
apache/tvm pull request #12519
Opened 2022-08-21 07:39 UTC by Lucien0

When compiling tvm with micro on the compiler which implements char as unsigned(such as arm-linux-gcc), there is an error:
`src/runtime/crt/graph_executor/load_json.c:218:12: error: result of comparison of constant -1 with expression of type 'char' is always false [-Werror,-Wtautological-constant-out-of-range-compare]`
`    if (ch == EOF || ch == '\r' || ch == '\n') {`
The reason is because the implementation of char is undefined, so it's better to specify here that it is signed.

2022-08-22 17:01 UTC, mehrdadh commented
@Lucien0 thanks! Let's wait for the CI to finish

2022-08-23 00:03 UTC, gromero commented
@Lucien0 @mehrdadh Could we used `int ch` like in other functions in `load_json.c`, like `JSONReader_NextObjectItem()`?

2022-08-23 01:41 UTC, mehrdadh requested changes
@gromero that's a good point! @Lucien0 can you try `int` instead?

2022-08-23 04:39 UTC, Lucien0 commented
done

2022-08-23 13:21 UTC, gromero approved these changes
LGTM. Thanks.

2022-08-25 00:45 UTC, mehrdadh approved these changes

2022-08-25 00:46 UTC, merged