[TIR] Enhance RemoveNoOp pass to remove negative loop
apache/tvm pull request #12836
Opened 2022-09-19 11:23 UTC by yincs-intellif

When after partition cascade ops, we sometimes meet some unused loops because their extents are negative. 
This PR enhance RemoveNoOp pass to remove these unused loop.

cc @Hzfengsy

2022-09-19 11:26 UTC, Hzfengsy approved these changes
Overall LGTM

2022-09-19 11:26 UTC, Hzfengsy commented on src/tir/transforms/remove_no_op.cc
> +  arith::Analyzer analyzer;
```suggestion
  std::unordered_map<const VarNode*, arith::IntSet> var_range_map_;
  arith::Analyzer analyzer_;
```
Also, please add the document

2022-09-20 07:10 UTC, wrongtest-intellif requested changes

2022-09-20 07:10 UTC, wrongtest-intellif commented on src/tir/transforms/remove_no_op.cc
> +    var_range_map_[op->loop_var.get()] = arith::IntSet::Interval(op->min, op->min + op->extent - 1);
recommend arith::IntSet::FromMinExtent() :)

2022-09-20 07:24 UTC, yincs-intellif commented on src/tir/transforms/remove_no_op.cc
> +    var_range_map_[op->loop_var.get()] = arith::IntSet::Interval(op->min, op->min + op->extent - 1);
OK

2022-09-20 07:24 UTC, yincs-intellif commented on src/tir/transforms/remove_no_op.cc
> +  arith::Analyzer analyzer;
OK

2022-09-21 02:46 UTC, wrongtest-intellif approved these changes

2022-09-21 03:03 UTC, merged