[TIR][Schedule] Add cache_buffer primitive to cache opaque buffer.
apache/tvm pull request #12939
Opened 2022-09-29 09:47 UTC by multiverstack

If a block both read and write a buffer, it cannot do cache read/write separately, otherwise dependency breaks. This primitive perform cache read & write together to keep IR correctness.

2022-10-01 03:14 UTC, multiverstack-intellif commented on src/tir/schedule/primitive/cache_read_write.cc
> +  block_info_read.scope->stage_pipeline = true;
my mistake, it should be always false here.

2022-10-01 03:14 UTC, multiverstack-intellif commented on src/tir/schedule/primitive/cache_read_write.cc
> +      // In cache_buffer case, alloc_buffer may be already exits.
good idea!

2022-10-08 07:29 UTC, wrongtest-intellif requested changes

2022-10-09 03:55 UTC, multiverstack-intellif commented on include/tvm/tir/schedule/schedule.h
> +   * \return The reindex stage block.
Thanks, fixed now.

2022-10-09 03:55 UTC, multiverstack-intellif commented on src/tir/schedule/primitive.h
> + * \return The reindex stage block.
Thanks, fixed now.

2022-10-09 03:55 UTC, multiverstack-intellif commented on src/tir/schedule/primitive/cache_read_write.cc
> +Array<StmtSRef> CacheBuffer(ScheduleState self, const StmtSRef& block_sref, int write_buffer_index,
Thanks, fixed now.

2022-10-09 03:59 UTC, multiverstack-intellif commented on src/tir/schedule/primitive/cache_read_write.cc
> +  self->Replace(scope_sref, new_scope, info.block_reuse);
This seems need big change to achieve, I'll add more checks at the beginning to prevent failure in the middle.

2022-10-09 03:59 UTC, multiverstack-intellif commented on src/tir/schedule/primitive/cache_read_write.cc
> +  BufferRegion region = GetBufferRegionFromBuffer(write_block->writes, buffer).value();
Thanks, more checks added in new commit.

2022-10-09 09:59 UTC, Hzfengsy approved these changes
LGTM. Thanks @multiverstack-intellif for adding new primitives!

2022-10-09 15:03 UTC, wrongtest-intellif approved these changes

2022-10-10 09:33 UTC, merged