[TIR][FIX] Fix crash when using 'if' without 'else' in TVMScript
apache/tvm pull request #13054
Opened 2022-10-12 13:55 UTC by WuSiYu

This commit fix the tvm's crash during auto-tune when having a 'if' statement which doesn't have a 'else' part in TVMScript.
It's cause in tvm's tir processing, in `VisitStmt_()` for IfThenElseNode its trying to visit the 'else' part (in TVMScript) whether it is exist.
So in this commit, an if logic is added in `VisitStmt_()` for IfThenElseNode, it will not visit the 'else' part if it is not exist.

2022-10-12 16:52 UTC, shingjan requested changes
Thanks for sending this! Looks fine to me. Would that be possible that some tests can be added to this PR so we will know if future changes will break this?

2022-10-12 19:36 UTC, junrushao approved these changes
LGTM

2022-10-13 08:01 UTC, Hzfengsy approved these changes

2022-10-13 08:02 UTC, WuSiYu commented
> Would that be possible that some tests can be added to this PR so we will know if future changes will break this?

Yes, a test has been added in test_tir_analysis_estimate_tir_flops.py

2022-10-13 08:07 UTC, shingjan approved these changes
Thanks for adding the test!

2022-10-13 11:32 UTC, WuSiYu commented
@tvm-bot rerun

2022-10-15 06:17 UTC, WuSiYu commented
I am not sure but it seem's like the CI is failed by the other ramdom reason, should I continue to try to rerun it?

2022-10-17 00:50 UTC, shingjan commented
@WuSiYu It seems that the `@tvm-bot rerun` doesn't go through for some reason. The last time CI failed for this PR is for this [test](https://github.com/apache/tvm/issues/13089), which has been reported. Feel free to retrigger the CI.

2022-10-17 18:21 UTC, merged