[docs][tvmc] Use correct argument to reuse tuning records
apache/tvm pull request #13302
Opened 2022-11-05 04:51 UTC by StrongerXi

As title. I found this while going through the [tutorial](https://tvm.apache.org/docs/tutorial/tvmc_python.html#saving-the-tuning-results).

If I understood correctly, `tuning_records` is meant for saving the generated tuning results, not reusing prior results.

2022-11-05 21:56 UTC, gromero requested changes
@StrongerXi Thanks for the fix! LGTM.

Could you just please update the Pull Request description text? Otherwise the PR will land in TVM's tree as a commit with a body text like "As title. I found this while ... " which is not appropriate for a commit message.

Please take a look at https://github.com/apache/tvm/blob/main/docs/contribute/pull_request.rst#commit-message-guideline for more details on how to right the description.

Thank you!

2022-11-05 22:06 UTC, StrongerXi commented
> @StrongerXi Thanks for the fix! LGTM.
> 
> Could you just please update the Pull Request description text? Otherwise the PR will land in TVM's tree as a commit with a body text like "As title. I found this while ... " which is not appropriate for a commit message.
> 
> Please take a look at https://github.com/apache/tvm/blob/main/docs/contribute/pull_request.rst#commit-message-guideline for more details on how to right the description.
> 
> Thank you!

Just did, let me know if it needs more tweaking:).

2022-11-06 14:20 UTC, gromero approved these changes

2022-11-06 14:23 UTC, merged

2022-11-06 14:25 UTC, gromero commented
@StrongerXi Thank you. The change is merged.