[Draft][CRT][microTVM] Enable USMP by default for AoTExecutor + CRT runtime
apache/tvm pull request #14107
Opened 2023-02-23 21:53 UTC by mehrdadh

Just opened the draft to see if CI failures.

2023-02-27 10:24 UTC, Mousius requested changes
In general this looks fine, I would also default `runtime` to `crt` though, set the new defaults ready for the next release.

Otherwise, there seems be a large unrelated refactor in this patch that confuses which files are effected by the actual USMP change - could you split that out into another PR?

2023-02-27 10:24 UTC, Mousius commented on src/relay/backend/aot_executor_codegen.cc
> +#include "../../target/parsers/mprofile.h"
```suggestion
```

2023-02-27 10:24 UTC, Mousius commented on tests/micro/arduino/test_arduino_error_detection.py
> +from . import utils
Any particular reason this is changing as part of this PR? Seems unrelated.

2023-02-27 10:24 UTC, Mousius commented on tests/micro/arduino/test_arduino_error_detection.py
> -    return test_utils.make_kws_project(board, microtvm_debug, workspace_dir, serial_number)
I think `test_utils` is clearer here, `utils` is a fairly vague term.

2023-03-01 20:26 UTC, mehrdadh commented
@Mousius thanks for the review. I removed unrelated changes. The rest are only removing some unused packages. PTAL.

2023-03-02 09:38 UTC, Mousius approved these changes
LGTM! Thanks @mehrdadh, these changes to introduce better default code paths are vital for the overall health of our codebase 😸

2023-03-02 09:38 UTC, merged