[Frontend][Paddle] [PaddlePaddle Hackathon 4] add convert support for affine_channel/p_norm/roi_align/softmax_with_cross_entropy
apache/tvm pull request #14826
Opened 2023-05-11 14:44 UTC by AndPuQing

Add support for converting the following Paddle OPs.

- [affine_channel](https://www.paddlepaddle.org.cn/documentation/docs/en/1.8/api/layers/affine_channel.html)
- [p_norm](https://www.paddlepaddle.org.cn/documentation/docs/en/2.2/api/paddle/norm_en.html#norm)
- [roi_align](https://www.paddlepaddle.org.cn/documentation/docs/en/2.5rc/api/paddle/vision/ops/roi_align_en.html)
- [softmax_with_cross_entropy](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/functional/softmax_with_cross_entropy_en.html#softmax-with-cross-entropy)

cc @jiangjiajun

2023-05-12 05:33 UTC, jiangjiajun requested changes

2023-05-12 05:33 UTC, jiangjiajun commented on tests/python/frontend/paddlepaddle/test_forward.py
> +
`fluid.layers.xxx` is deprecated, and will be removed in next version, please use other api, or just remove this operator

2023-05-16 06:49 UTC, jiangjiajun approved these changes
Please modify the title to "[Frontend][Paddle] [PaddlePaddle Hackathon 4] add convert support for p_norm/roi_align/softmax_with_cross_entropy", since the `affine_channel` is removed.

2023-05-17 02:12 UTC, jiangjiajun commented
@junrushao Could you help to merge this PR? I found that I'am still a `contributor` not a `reviewer`...

2023-05-17 03:14 UTC, junrushao approved these changes

2023-05-17 03:14 UTC, merged