[CPP_RPC] export listdir for RPC
apache/tvm pull request #15537
Opened 2023-08-12 15:46 UTC by Ever-Kid

This PR register `tvm.rpc.server.listdir` using `ListDir` and export it in python frontend for PRC use.

2023-08-16 10:55 UTC, wrongtest-intellif requested changes

2023-08-16 10:55 UTC, wrongtest-intellif commented on apps/cpp_rpc/rpc_env.cc
> +std::vector<std::string> ListDir(const std::string& dirname);
Is the implementation missing?

2023-08-16 10:55 UTC, wrongtest-intellif commented on apps/cpp_rpc/rpc_env.cc
> +      ret.append(d.append(","));
Could we use ostringstream here?

2023-08-16 10:55 UTC, wrongtest-intellif commented on python/tvm/rpc/client.py
> +            The relative location to remote temp folder.
It would be great to describe the return type and split token.

2023-08-16 11:31 UTC, Ever-Kid commented on apps/cpp_rpc/rpc_env.cc
> +std::vector<std::string> ListDir(const std::string& dirname);
already coded downside the same file

2023-08-21 02:10 UTC, wrongtest-intellif approved these changes

2023-08-24 10:37 UTC, merged