[Unity][Transform] Implement UpdateParamStructInfo
apache/tvm pull request #16305
Opened 2023-12-29 18:55 UTC by Lunderberg

Provide a convenience method to update parameter struct info, propagating any changes to internal bindings and return type.

2024-01-02 23:04 UTC, slyubomirsky requested changes
This seems reasonable, but I found it a little difficult to be certain of the logic. You are using `VisitVarDef` but are ignoring vars defined inside `SeqExpr`s, so I take it that this will update only function parameters (per the name). Is that correct? It should perhaps be pointed out. I'm not sure if it would be simpler to override the function node case instead of `VisitVarDef`.

2024-01-03 15:02 UTC, Lunderberg commented on src/relax/transform/update_param_struct_info.cc
> +  bool inside_expr_{false};
Good point, it probably would have been better to name it as `inside_function_body_`.  It has been removed in the updated implementation.

2024-01-03 15:10 UTC, Lunderberg commented
> You are using VisitVarDef but are ignoring vars defined inside SeqExprs, so I take it that this will update only function parameters (per the name). Is that correct?

That is correct.  Only parameters would be updated, and variable bindings within the function body would have their struct info inferred.

> I'm not sure if it would be simpler to override the function node case instead of VisitVarDef.

I initially ran into some issues with overriding the `Expr VisitExpr_(const FunctionNode*)` mutator, mostly because it was difficult without copy-pasting the entire `ExprMutator` implementation.  In order to delegate to the base class's mutator, it would need to first construct a `Function` object with updated parameters, and then pass that to the base class.  However, that ran into issues with the validity-checking in the `Function` constructor, since the body of the function wasn't yet updated.

Taking another look at it, it looks like it can be moved to the `VisitExpr_(const FunctionNode*)` by using `func.CopyOnWrite()` to avoid going through the normal constructor.  I agree that this is simpler, and have updated the PR to use the less roundabout implementation.

2024-01-03 23:29 UTC, slyubomirsky approved these changes
Thank you for the changes.

2024-01-04 17:02 UTC, merged