[CUDA] BF16 support
apache/tvm pull request #7014
Opened 2020-12-02 14:45 UTC by hgt312

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

2021-03-03 22:01 UTC, tqchen commented
@yzhliu @hgt312  can we please followup on this PR?

cc @vinx13 @masahi

2021-03-04 02:36 UTC, jcf94 requested changes
Plz rebase this branch

2021-03-04 02:36 UTC, jcf94 commented on tests/python/unittest/test_target_codegen_cuda.py
> +    # test_unrolled_vectorization()
Uncommon these tests.

2021-03-04 03:31 UTC, jcf94 commented
> @yzhliu @hgt312 can we please followup on this PR?
> 
> @jcf94 would be great if you can help to manage this PR (also cc @vinx13 @masahi)

@tqchen Thanks! I'd love to help.

If @hgt312 don't have time to finish these remaining issues, I can help clean them this weekend.

2021-03-06 10:24 UTC, jcf94 approved these changes
Thanks! @hgt312

2021-03-06 10:24 UTC, merged