[BugFix][Android RPC] fix build bugs and improve android_rpc experience
apache/tvm pull request #7680
Opened 2021-03-17 06:56 UTC by new-TonyWang

Fix the following bugs:
1. gradle build fail due to Execution failed for` task ':app:buildJni'. Process 'command 'sh'' finished with non-zero exit value 2`
2. run python android_rpc_test.py and wait for so long but finally got a `Connect to x.x.x.x:5001 `failed
3. RPCActivity may starts up not once but twice

@yzhliu @eqy @tqchen

2021-03-17 07:07 UTC, new-TonyWang commented
There still remains some maven errors in jvm due to the incompatible java version and lack of jni head file paths in 'jvm/native/linux-x86_64', maybe the windows have the same error but I have no windows pc to test it. I think one  way is to require user to set a $JAVA_HOME in path, then we are able to set the jni head file paths easily.

2021-03-19 05:47 UTC, new-TonyWang reviewed
ok

2021-03-26 09:46 UTC, liangfu requested changes
Thanks for improving android_rpc.

I left some comments, otherwise looks good.

2021-03-26 09:46 UTC, liangfu commented on apps/android_rpc/.gitignore
> +/gradle
please add newline at EOF

2021-03-26 09:46 UTC, liangfu commented on apps/android_rpc/app/.gitignore
> +/libs
please add newline at EOF

2021-03-26 09:46 UTC, liangfu commented on apps/android_rpc/app/build.gradle
> +
please remove extra blank lines.

2021-03-26 09:46 UTC, liangfu commented on apps/android_rpc/app/src/main/jni/CMakeLists.txt
> +
please remove extra blank lines, and some similar ones in the following.

2021-03-26 09:46 UTC, liangfu commented on apps/android_rpc/app/src/main/jni/CMakeLists.txt
> +endif()
please add newline at EOF

2021-03-26 09:46 UTC, liangfu commented on apps/android_rpc/app/src/main/jni/CMakeLists.txt
> +            tvm4j_runtime_packed
please keep indentation consistent.

2021-03-26 09:46 UTC, liangfu commented on apps/android_rpc/app/build.gradle
> +                //jniLibs.srcDirs = ['src/main/libs']
please remove unused code.

2021-03-26 09:46 UTC, liangfu commented on apps/android_rpc/app/src/main/java/org/apache/tvm/tvmrpc/MainActivity.java
> +
remove extra blank lines.

2022-01-19 20:24 UTC, jroesch commented
This PR appears to be out of date, please feel free to reopen it if this is not the case.

As part of the new year we are attempting to triage the project's open pull requests to ensure that code which
is ready for review and/or merging receives adequate attention.

Thanks again for your contribution, and feel free to reach out to discuss these changes.

2022-01-19 20:24 UTC, closed without merging