[TVMC] Runner.py Updates
apache/tvm pull request #7779
Opened 2021-03-31 22:43 UTC by CircleSpin

This PR does three things:
1) Makes hostname optional in run_module
2) Makes device mandatory in run_module
3) Changes the runner time measurements to be in milliseconds rather than seconds (with additional test updates)

2021-03-31 22:44 UTC, CircleSpin commented
@jwfromm @mdw-octoml @leandron @comaniac 

Please let me know your thoughts :)

2021-03-31 22:50 UTC, comaniac requested changes
First, if we agree with this change, your need to adjust the argument order. A required position argument cannot be placed after an optional argument. Second, I didn't find the logic of handling the default value when `hostname` is `None`, nor I'm not sure if this makes sense to make it optinoal.

2021-03-31 22:50 UTC, comaniac commented on python/tvm/driver/tvmc/runner.py
> +    print("%s\n%s\n" % (header, stats))
Why print?

2021-03-31 23:52 UTC, jwfromm commented
@comaniac, if you look at the full function, its already handling `hostname=None` and requiring that `device` is set. The change to the arguments here just more closely matches the actual behavior.

2021-04-01 00:16 UTC, comaniac commented
> @comaniac, if you look at the full function, its already handling `hostname=None` and requiring that `device` is set. The change to the arguments here just more closely matches the actual behavior.

You're right. Yeah then it makes sense to adjust the arguments to align the actual behavior. Then please change the order accordingly and update the type in docstring.

2021-04-01 19:09 UTC, comaniac approved these changes
LGTM
cc @leandron

2021-04-01 19:27 UTC, jwfromm approved these changes

2021-04-07 00:05 UTC, merged

2021-04-07 00:06 UTC, jwfromm commented
Thanks @CircleSpin and @comaniac. This is now merged.