[Topi & Relay] Add quantization support for the vision transform model in GPU
apache/tvm pull request #7814
Opened 2021-04-09 11:34 UTC by huochaitiantang

We submit this PR to add quantization support for the [vision transform (vit)](https://arxiv.org/abs/2010.11929) model in GPU. The main change is as follows:

1, In vit model,  time-consuming operators are batch_matmul,  so we first add the compute and schedule of `batch_matmul_int8.cuda` in tvm.topi.cuda

2, To support the quantization of batch_matmul, we then add `batch_matmul_rewrite` and `BatchMatmulRealize` in tvm.relay.quantize 

3, The kl -divergence calibrate could not preserve the accuracy of vit model well, so we add the `_percentile_scale` function 

For the vit-B32-224 model, the performance is as follows:

- Top-1 accuracy in Imagenet validation
  - paper: 73.38
  - nonofficial-model-fp32: 73.27
  - nonofficial-model-int8: 72.78

- The latency in GTX1660 GPU
  - nonofficial-model-fp32: 10.32 ms
  - nonofficial-model-int8: 4.93 ms

Thanks for your review! @jcf94 @tqchen

2021-04-09 11:51 UTC, XHPlus commented
Thanks for the reviewer. We will keep updating more results for other ViT models and contributing more quantization calibration algorithms.

2021-04-11 08:04 UTC, jcf94 requested changes
Thanks! @huochaitiantang
This PR looks great! I have only few comments.

2021-04-12 02:55 UTC, huochaitiantang commented on python/tvm/relay/op/strategy/cuda.py
> +            name="batch_matmul_int8.cuda",
We add plevel=10 for the batch_matmul_int8.cuda, which is the same as dense_int8.cuda

2021-04-12 03:02 UTC, huochaitiantang commented on tests/python/nightly/quantization/test_quantization_accuracy_for_vit.py
> +        os.system("wget https://github.com/TheGreatCold/tvm-vit/raw/master/{}".format(onnx_path))
Thanks for your review. We updated the download codes based on your suggestion. Besides, the wget method is not compatible on different platforms, so we use the urllib library instead.

2021-04-13 02:11 UTC, jcf94 approved these changes
Thanks! @huochaitiantang @XHPlus . Have fun with TVM. Looking forward to see more contributions from you!

2021-04-14 02:10 UTC, merged