[Frontend] Speed up Fold Constant
apache/tvm pull request #8208
Opened 2021-06-07 21:44 UTC by mbrookhart

@masahi 

This utiliy was creating a new IRModule from the provided expression if the provided module was None. This isn't strictly necessary, the use cases are correct if we pass in an empty IRModule. The WellFormed check inside IRModule.from_expr was actually taking a lot of the time when importing large ONNX models. This change gets me a 2.6x speedup on importing the large NLP model I'm playing with today.

2021-06-08 06:40 UTC, jcf94 requested changes
Do we have a UT for the `fold_const` with mod input as None?

If not, I suggest to add one for that.

2021-06-08 14:43 UTC, mbrookhart commented
We use it in dozens of places in the ONNX importer with mod=None, if there was a problem, ~1/3 of the onnx unit tests would have failed. I'm not sure any of the utilities in the frontend/common.py file are actually tested? https://github.com/apache/tvm/blob/main/tests/python/frontend/test_common.py

2021-06-09 01:41 UTC, jcf94 approved these changes
OK, then I don't have any other questions.

2021-06-09 02:35 UTC, masahi approved these changes

2021-06-09 02:35 UTC, merged