Add a `--context-path` for build.sh
apache/tvm pull request #8557
Opened 2021-07-26 11:10 UTC by leandron

Add a `--context-path` for build.sh, allowing to test Dockerfiles in different directories, and still get relative paths to work.

* Add new option --context-path to build.sh
* Keeps the default as the `dirname` of the Dockerfile, so
  no changes expected in the current behaviour

cc @Mousius @areusch @mehrdadh for reviews

2021-07-26 11:57 UTC, Mousius requested changes

2021-07-26 11:57 UTC, Mousius commented on docker/build.sh
> +    DOCKER_CONTEXT_PATH="$1"
To be consistent with the rest of this file, we should use `$2` here and `shift 2` lower down.

2021-07-26 13:22 UTC, Mousius approved these changes

2021-07-26 15:40 UTC, mehrdadh approved these changes

2021-07-26 15:40 UTC, mehrdadh commented
@leandron LGTM. Thanks for this change!

2021-07-26 15:41 UTC, areusch commented
just curious what's the use case for this change?

2021-07-26 21:07 UTC, leandron commented
> just curious what's the use case for this change?

We have some tooling that will use Dockerfiles out of tree (in a temp directory), but it needs to keep the context pointing to the tree, in order to resolve relative paths.

2021-07-27 15:38 UTC, leandron commented
It seems CI is happy now, can I get a review and a merge if you're happy? @areusch

2021-07-27 16:19 UTC, areusch approved these changes

2021-07-27 16:19 UTC, merged