[microTVM] Fix warnings on Zephyr tests
apache/tvm pull request #8740
Opened 2021-08-12 19:11 UTC by gromero

Fix the following warning message on Zephyr tests:

DeprecationWarning: Please use input parameter mod (tvm.IRModule)
instead of deprecated parameter mod (tvm.relay.function.Function)

Signd-off-by: Gustavo Romero <gustavo.romero@linaro.org>

Thanks for contributing to TVM!   Please refer to guideline https://tvm.apache.org/docs/contribute/ for useful information and tips. After the pull request is submitted, please request code reviews from [Reviewers](https://github.com/apache/incubator-tvm/blob/master/CONTRIBUTORS.md#reviewers) by @ them in the pull request thread.

2021-08-12 19:25 UTC, Mousius requested changes

2021-08-12 19:25 UTC, Mousius commented on tests/micro/zephyr/test_zephyr_aot.py
> +    func = tvm.IRModule.from_expr(func)
Given this isn't the function anymore, maybe we should go with `ir_mod` or `mod` ?

2021-08-13 12:06 UTC, gromero commented
@Mousius @areusch Thanks for the quick review! I've just pushed https://github.com/apache/tvm/commit/00b49dc40d94a75dfb551785c52dff4634dba0ef addressing the comment from Chris.

2021-08-13 13:17 UTC, Mousius approved these changes
Thanks for the update @gromero, LGTM!

2021-08-14 14:35 UTC, gromero commented
@areusch @leandron I'm wondering if you could please collect it? :)

2021-08-16 08:08 UTC, leandron approved these changes
LGTM, thanks @gromero and @Mousius!

2021-08-16 08:09 UTC, merged